import Foundation

struct StringConstants {
  static let validField: String = "true"
  static let notValidField: String = "false"
  static let warningField: String = "alert"
  static let warningTitle: String = "Warning!"
  static let defaultEmailPlaceholder: String = "jane@example.com"
  static let defaultPasswordPlaceholder: String = "••••••••••••"
  static let defaultSearchPlaceholder: String = "Search"
  static let defaultCryptedCharacter: String = "•"
  static let defaultStoryboardName: String = "Main"
  static let customeStoryBoardName: String = "CustomAlert"
  static let customeAlertIdentifier: String = "customAlert"
  static let emailRegexPattern: String = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"
  static let selfMatchRegexPattern: String = "SELF MATCHES %@"
  static let showPassword: String = "show"
  static let hidePassword: String = "hide"
  static let defaultAlertTitle: String = "Error !"
  static let successTitle: String = "Success!"
  static let successEmailFormat: String = "Success Email Format"
  static let wrongEmailFormat: String = "Wrong Email Format"
  static let emptyEmailField: String = "Empty Email Field"
  static let successPasswordFormat: String = "Success Password format"
  static let emptyPasswordField: String = "Empty Password Field !"
  static let beCarefullPassword: String = "Be Careful Your Password Is Weak"
  static let defaultAlertAgree: String = "OK"
  static let defaultAlertMessage: String = "Please try again"
  static let incorrectUserPassword: String = "Incorrect User Password !"
  static let accountNotExist: String = "Account Doesn't Exist !"
  static let fromRegisterToLogin: String = "registertoLogin"
  static let fromLoginToHome: String = "loginToMain"
  static let fromHomeToDetails: String = "homeToDetails"
  static let fromSearchToDetails: String = "searchToDetails"
  static let emptyFieldAlertMessage: String = "Please Fill the Blanks :("
  static let invalidEmailAlertMessage: String = "Incorrect Email Format :("
  static let emptyField: String = ""
}
